bitcoin_dbt:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'CRYPTO_DB') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'compute_wh') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'RAW') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
