# Date range for the bitcoin market pipeline
START_DATE = "2024-01-01"
END_DATE = "2026-12-31"

# Snowflake config
SNOWFLAKE_DATABASE = "CRYPTO_DB"
SNOWFLAKE_RAW_SCHEMA = "RAW"
SNOWFLAKE_BRONZE_SCHEMA = "ANALYTICS_BRONZE"
SNOWFLAKE_SILVER_SCHEMA = "ANALYTICS_SILVER"
SNOWFLAKE_GOLD_SCHEMA = "ANALYTICS_GOLD"

# CoinGecko
COINGECKO_URL = "https://api.coingecko.com/api/v3/coins/markets"
COINGECKO_VS_CURRENCY = "usd"
COINGECKO_PER_PAGE = 250

# Raw table
RAW_TABLE_NAME = "CRYPTO_MARKET_RAW"
